feat: ゲーム終了時のスコア・順位算出、GameOverWindowから新しいゲームを始める（storeの初期化）
Recursion-Group-P/blokee pull request #55
Opened 2022-06-12 22:23 UTC by hayato0309

### Issue: #47 

## 目的
以下機能の実装
* ゲームの終了判定
* ゲーム終了時にモーダル表示
* スコア計算
* 順位計算
* モーダル内の「GO TO SETTINGS PAGE」をクリックすると、Settings Pageに遷移し、今までのゲームデータが初期化される
（同じ設定でゲームを始める機能は実装が難しかったので保留。実装しかけたコードはコメントアウトで残している）

## 実装の概要
* ゲーム終了時モーダルウィンドウ表示
  * playerが持っているscoreとremainingTimeをevaluation.js内で計算
※今まではplayerにtimeを持たせないようにしていたが、今回、playerにremainingTimeとして持たせるように変更
※remainingTimeは、timer停止の度にstoreのactionを呼び出して更新

* スコア計算
  * ピースを使い切ったら+15pt（evaluation.jsのgetFinalResult()）
  * 最後に１マスのピースを使用で+5pt（evaluation.jsのgetLastOnePieceBonus(), checkIfTheLastPieceHasOnlyOneCell()）
※ボーナスポイントはsrc/constants/index.jsで定義

* 順位計算
  * scoreの降順、remainingTimeの降順でソート
  * ソートした配列（sortedFinalResultをGameOverWindowでv-for）

* GameOverWindowから新しいゲームを始める
  * GameOverWindowの「GO TO SETTINGS PAGE」をスリックすると、SettingsPageに遷移すると同時にstoreを初期化する
  * storeの初期化は、store-game.jsのformatState()
※同じSettingsでゲームを始める機能は、難しかったので保留

## レビューして欲しいところ
* evaluation.jsへのロジック切り出しはこんな感じでOKかどうか

2022-06-13 15:58 UTC, tkwonn requested changes

2022-06-13 15:58 UTC, tkwonn commented on src/model/evaluation.js
> +    }
以下のように変更するともっとスッキリすると思います
```
checkIfGameIsOver() {
        // 1. 全てのplayerが全てのピースを使い切ったか確認
        let allPlayersUsedUpAllPieces = true;
        for (let i = 0; i < this.players.length; i++) {
            let remainingPieces = this.players[i].remainingPieces;
            allPlayersUsedUpAllPieces = this.checkIfUsedUpAllPieces(remainingPieces);
        }

        // 2. 全てのplayerのoutOfGameがtrueになっているか確認
        // outOfGameがtrueのplayerをカウント
        let outOfGameCount = 0;
        for (let i = 0; i < this.players.length; i++) {
            if (this.players[i].outOfGame === true) outOfGameCount++;
        }
        // let allPlayersOutOfGame = true;
        // if (outOfGameCount < this.players.length) allPlayersOutOfGame = false;

        // // 1, 2のどちらかがtrueの時にゲームを終了する
        // let gameIsOver = allPlayersUsedUpAllPieces || allPlayersOutOfGame;

        return allPlayersUsedUpAllPieces || outOfGameCount == 4;
    }
```

2022-06-13 15:58 UTC, tkwonn commented on src/components/GameOverWindow.vue
>        </div>
v-for(r, index) in finalResult"は少し連想しにくいかもですね。

in OOの部分を複数系にして以下のようにすれば、もっとわかりやすいかと思います。
v-for(result, index) in results"

2022-06-13 15:58 UTC, tkwonn commented on src/components/GameOverWindow.vue
> +      </div> -->
mapStateでGameSettingsで必要な値を取得してその値をsetGameSettings actionに渡す方法はどうですか？

```
...mapState('game', ['numberOfPlayers', 'timeForEachPlayers, 'startPoint'.....)
...mapActions('game', ['setGameSettings']

newGameWithSameSettings() {
     this.setGameSettings({numberOfPlayers: this.numberOfPlayers, timeForEachPlayers: ....)
}
```

2022-06-13 15:58 UTC, tkwonn commented on src/store/store-game.js
> +  },
毎回アップデートするかどうかわからないので、関数の命名的に別のに変えたほうがいいですね。
checkIfWinnerExistとか、checkIfGameIsOverとか

2022-06-13 16:00 UTC, tkwonn commented
@hayato0309 
ゲーム結果のソートであったり、evaluation.jsでの処理は問題いです！

2022-06-13 21:23 UTC, hayato0309 commented
@tkwonn
レビューありがとうございます！
修正します！

また「同じ設定でゲームをPlayする」機能に関して頂いたコメントですが、
確かにその方法で実装できそうな感じがしますね！
ありがとうございます🙇‍♂️やってみます。

2022-06-13 21:24 UTC, haruki111 commented on src/model/evaluation.js
> +    }
横からすみません
for...of使うともう少しスッキリします
既知でしたらすみません
```js
for(const player of this.players){
    const remainingPieces = player.remainingPieces;
    ...
}
```
「 i 」がどこで使われるか、考えなくて済むので楽だと思ってます。

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/for...of

コメント僕も見習いたいです
失礼しましたm(._.)m

2022-06-13 21:51 UTC, hayato0309 commented
@tkwonn 
一旦リファクタリングの部分だけ完了してコミットしました！
ご確認お願いします🙇‍♂️

2022-06-13 22:42 UTC, tkwonn commented on src/model/evaluation.js
> +    }
@haruki111 ハルキさんありがとうございます！
@hayato0309  for.. of使えそうな部分今回のプロジェクトで多いので使ってみてください！
たしかPieceAlterかPieceSelectorとかでもそのように修正できそうな所があったような気がします。

2022-06-13 22:54 UTC, tkwonn approved these changes

2022-06-13 22:54 UTC, merged

2022-06-14 03:58 UTC, hayato0309 commented on src/model/evaluation.js
> +    }
@haruki111 
ありがとうございます！
ちゃんと目的意識をもってfor...ofを使ったことがなかったので、とても勉強になりました。
コードがかなりスマートになりそうです！

@tkwonn 
ブランチ新たに切ってリファクタリングですかね？
（Pass機能のバグ修正プルリクと返信重複してます。。ややこしくてすみません！）